# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publicLibrary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13publicLibrary.proto\x12\x06protos\"\xcc\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12%\n\x05genre\x18\x04 \x01(\x0e\x32\x16.protos.Book.GenreType\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\"X\n\tGenreType\x12\x0b\n\x07\x46iction\x10\x00\x12\x0e\n\nNonFiction\x10\x01\x12\x0b\n\x07History\x10\x02\x12\x0e\n\nPhilosophy\x10\x03\x12\x11\n\rSocialScience\x10\x04\"I\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tbiography\x18\x02 \x01(\t\x12\x1e\n\x08writings\x18\x03 \x03(\x0b\x32\x0c.protos.Book\"\xae\x01\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\t\x12\x1c\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0c.protos.BookH\x00\x12\x30\n\x06status\x18\x03 \x01(\x0e\x32 .protos.InventoryItem.ItemStatus\"&\n\nItemStatus\x12\r\n\tAvailable\x10\x00\x12\t\n\x05Taken\x10\x01\x42\x0c\n\nsingleBook\"/\n\x11\x43reateBookRequest\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.protos.Book\"1\n\x12\x43reateBookResponse\x12\x1b\n\x13\x63onfirmationMessage\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"-\n\x0fGetBookResponse\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.protos.Book2\x97\x01\n\x10InventoryService\x12\x45\n\nCreateBook\x12\x19.protos.CreateBookRequest\x1a\x1a.protos.CreateBookResponse\"\x00\x12<\n\x07GetBook\x12\x16.protos.GetBookRequest\x1a\x17.protos.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publicLibrary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=32
  _BOOK._serialized_end=236
  _BOOK_GENRETYPE._serialized_start=148
  _BOOK_GENRETYPE._serialized_end=236
  _AUTHOR._serialized_start=238
  _AUTHOR._serialized_end=311
  _INVENTORYITEM._serialized_start=314
  _INVENTORYITEM._serialized_end=488
  _INVENTORYITEM_ITEMSTATUS._serialized_start=436
  _INVENTORYITEM_ITEMSTATUS._serialized_end=474
  _CREATEBOOKREQUEST._serialized_start=490
  _CREATEBOOKREQUEST._serialized_end=537
  _CREATEBOOKRESPONSE._serialized_start=539
  _CREATEBOOKRESPONSE._serialized_end=588
  _GETBOOKREQUEST._serialized_start=590
  _GETBOOKREQUEST._serialized_end=620
  _GETBOOKRESPONSE._serialized_start=622
  _GETBOOKRESPONSE._serialized_end=667
  _INVENTORYSERVICE._serialized_start=670
  _INVENTORYSERVICE._serialized_end=821
# @@protoc_insertion_point(module_scope)
